export const CONDITIONS: Record<number, { name: string; description: string }> = {
  1: { name: "Sangrando", description: "Perde 1 ponto de vida por rodada até ser estabilizado." },
  2: { name: "Atordoado", description: "Perde a próxima ação; ataques contra você têm vantagem." },
  3: { name: "Derrubado", description: "Você cai no chão; levantar consome 1 ação." },
  4: { name: "Amedrontado", description: "Não pode se aproximar da fonte de medo; -2 em testes." },
  5: { name: "Envenenado", description: "Desvantagem em testes físicos; perde 1d4 vida por cena." },
  6: { name: "Quebrado Psicologicamente", description: "Não pode realizar ações ofensivas." },
  7: { name: "Agarrado", description: "Não pode se mover; precisa vencer teste para escapar." },
  8: { name: "Silenciado", description: "Não pode falar ou emitir comandos verbais." },
  9: { name: "Lentificado", description: "Metade da movimentação; perde metade das ações rápidas." },
  10: { name: "Exausto", description: "-2 em todos os testes; velocidade -50%." },

  11: { name: "Sobrecarregado (Implantes)", description: "Um implante falha; -2 em testes ligados a ele." },
  12: { name: "Sobrecarga Neural", description: "Perde sua reação da rodada." },
  13: { name: "Apagado", description: "Inconsciente até ser curado ou após 1d6 minutos." },
  14: { name: "Surtando", description: "Ataca a criatura mais próxima, aliado ou inimigo." },
  15: { name: "Concentrado", description: "+2 em testes de precisão ou hack." },
  16: { name: "Inspirado", description: "+2 em testes sociais e de moral." },
  17: { name: "Invisível / Oculto", description: "Ataques contra você têm desvantagem." },
  18: { name: "Encurralado", description: "Mover-se provoca ataque de oportunidade." },
  19: { name: "Escaneado", description: "Dados copiados; risco de cyberpsicose se traumático." },
  20: { name: "Queimando", description: "Perde 1d6 vida por rodada até apagar as chamas." },

  21: { name: "Congelado de Medo", description: "Não age por 1 rodada." },
  22: { name: "Em Pânico", description: "Corre na direção oposta durante o turno." },
  23: { name: "Hackeado (Leve)", description: "Sistema trava; -1 em testes." },
  24: { name: "Hackeado (Severo)", description: "Perde uma ação por turno." },
  25: { name: "Corrompido", description: "Implante age de forma imprevisível." },
  26: { name: "Intoxicado (Droga Leve)", description: "+2 sociais; -2 percepção." },
  27: { name: "Drogado (Forte)", description: "+4 Força por 3 turnos; depois Exausto." },
  28: { name: "Cego Temporariamente", description: "Falha em testes visuais; ataques com desvantagem." },
  29: { name: "Surdo Temporariamente", description: "Desvantagem para detectar ameaças." },
  30: { name: "Desesperado", description: "+2 ataques; -2 defesa." },

  31: { name: "Enfurecido", description: "+3 ataque; -3 defesa." },
  32: { name: "Confuso", description: "50% de chance de agir errado." },
  33: { name: "Amordaçado", description: "Não ativa implantes verbais." },
  34: { name: "Silenciado Digitalmente", description: "Comunicações travadas." },
  35: { name: "Rastreamento Ativo", description: "Localização revelada a outra facção." },
  36: { name: "Contaminado Biologicamente", description: "-2 testes físicos; risco de espalhar doença." },
  37: { name: "Contaminado Quimicamente", description: "-2 em tudo por 1d4 horas." },
  38: { name: "Marcado por Laser", description: "Ataques contra você têm +2 acerto." },
  39: { name: "Alvo Térmico", description: "Pode ser rastreado por drones no escuro." },
  40: { name: "Pressurizado", description: "+2 dano corpo a corpo." },

  41: { name: "Arranhado na Lente Ocular", description: "-2 em testes de mira." },
  42: { name: "Ressonância Neural", description: "-1 em testes mentais." },
  43: { name: "Sincronizado", description: "+2 em testes técnicos." },
  44: { name: "Desalinhado", description: "Desvantagem em ações específicas." },
  45: { name: "Eufórico", description: "+1 em tudo por 3 turnos; depois Exausto." },
  46: { name: "Suprimido", description: "Não avança; -2 ataques." },
  47: { name: "Radiação Baixa", description: "Perde 1 HP por minuto." },
  48: { name: "Radiação Alta", description: "Perde 1d6 HP por minuto; risco de mutação." },
  49: { name: "Choque Elétrico", description: "Sem reação e implantes por 1 rodada." },
  50: { name: "Blindado", description: "Dano físico reduzido em 50%." },

  51: { name: "Sob Fogo Cruzado", description: "Desvantagem em ataque e movimento." },
  52: { name: "Prone Técnico", description: "+2 para reparar." },
  53: { name: "Dano Sináptico", description: "-2 Inteligência." },
  54: { name: "Flashbang", description: "Ataques à distância com desvantagem." },
  55: { name: "Cibertremor", description: "-2 precisão." },
  56: { name: "Sombra de Dados", description: "-2 social; dificuldade reconhecer aliados." },
  57: { name: "Viciado", description: "Sem dose: -2 em tudo." },
  58: { name: "Viciado Grave", description: "Sem dose: -4 em tudo + tremores." },
  59: { name: "Rastreador Biológico", description: "DNA ou cheiro rastreável." },
  60: { name: "Rastreador Digital", description: "Pacotes de dados interceptáveis." },

  61: { name: "Protetor", description: "+2 para revidar se aliado for atacado." },
  62: { name: "Em Guarda", description: "+2 defesa." },
  63: { name: "Vulnerável", description: "Ataques causam +1d4 dano." },
  64: { name: "Blindado Mentalmente", description: "Imune a medos leves." },
  65: { name: "Zangado", description: "+2 no primeiro ataque do turno." },
  66: { name: "Calmo", description: "-2 intimidação contra você." },
  67: { name: "Adrenalina Ativa", description: "+1 ação rápida." },
  68: { name: "Sem Ar", description: "Não fala nem usa habilidades que exigem ar." },
  69: { name: "Afogado", description: "Perde 1d6 vida por turno." },
  70: { name: "Empurrado", description: "Deslocado alguns metros; pode cair." },

  71: { name: "Isolado Digitalmente", description: "Implantes desligados por jammer." },
  72: { name: "Saturado de Estresse", description: "Falha gera Pânico." },
  73: { name: "Levantado", description: "+2 ataque corpo a corpo." },
  74: { name: "Bêbado", description: "-2 ataques; +1 carisma." },
  75: { name: "Loucura Temporária", description: "Alucinações por 1d10 minutos." },
  76: { name: "Loucura Permanente (Leve)", description: "Desvantagem mental até tratamento." },
  77: { name: "Doente", description: "-2 ações físicas prolongadas." },
  78: { name: "Energizado", description: "Movimento +50%." },
  79: { name: "Distraído", description: "Desvantagem em percepção." },
  80: { name: "Invisível para Máquinas", description: "Câmeras não detectam." },

  81: { name: "Caçado", description: "Uma facção está atrás de você." },
  82: { name: "Protegido pela Lei", description: "Guardas priorizam ajuda." },
  83: { name: "Sujo", description: "-2 social com NPCs exigentes." },
  84: { name: "Abençoado", description: "Primeira falha do dia é ignorada." },
  85: { name: "Fadigado de Hack", description: "-2 ações digitais." },
  86: { name: "Incendiário", description: "Ataques causam +1d4 fogo." },
  87: { name: "Carregado Eletricamente", description: "+1d4 elétrico desarmado." },
  88: { name: "Corrompido por Malware", description: "50% de chance de falha." },
  89: { name: "Nanites Ativos", description: "Regenera 1 HP por rodada." },
  90: { name: "Em Luto", description: "-2 social; +1 ataque por vingança." },

  91: { name: "Ferido Gravemente", description: "Metade das ações; penalidade severa." },
  92: { name: "Desorientado", description: "Movimento aleatório no primeiro turno." },
  93: { name: "Sangue Frio", description: "+2 ataques furtivos." },
  94: { name: "Exposto", description: "+2 ataques contra você." },
  95: { name: "Protegido por Drones", description: "+2 defesa enquanto ativos." },
  96: { name: "Sob Fogo de Sniper", description: "Mover-se provoca ataque imediato." },
  97: { name: "Em Alerta Máximo", description: "+2 percepção; +1 ataque." },
  98: { name: "Hiperconectado", description: "Controla dois dispositivos." },
  99: { name: "Glitchado", description: "Perde 1 ação aleatória." },
  100:{ name: "Risco de Cyberpsicose", description: "+10% imediato na barra." },
};
